[package]
name = "jj"
version = "0.1.0"
authors = ["Logan Barnett <logustus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Included just so we can reference the Error type from Command's Output.
futures-io = "0.3.15"
reqwest = { version = "0.11.3", features = ["blocking", "json"] }
serde = { version = "1.0.125", features = ["derive"] }
serdeconv = "0.2.1"
structopt = "0.3.21"
